# Generated by Django 4.2 on 2025-11-03 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("DG", "Dog"),
                            ("CT", "Cat"),
                            ("RD", "Rodent"),
                            ("RB", "Rabbits"),
                            ("LZ", "Lizards"),
                            ("SN", "Snakes"),
                            ("HR", "Horses"),
                            ("TR", "Turtles"),
                        ],
                        default="DG",
                        max_length=2,
                    ),
                ),
                ("owner", models.CharField(max_length=150)),
                ("dob", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Vaccines",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("CI", "Canine Influenza"),
                            ("LD", "Lyme Disease"),
                            ("BD", "Bordatella"),
                            ("RB", "Rabies"),
                            ("PV", "Parvovirus"),
                            ("PI", "Parainfluenza"),
                            ("CH", "Canine Hepatitis"),
                            ("CP", "Canine Parainfluenza"),
                            ("DV", "Dog Vaccine"),
                            ("LV", "Leptospirosis Vaccine"),
                            ("GD", "Giardia"),
                            ("KC", "Kennel Cough"),
                        ],
                        default="CI",
                        max_length=2,
                    ),
                ),
                ("administered", models.DateField()),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="petz.pets"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Allergies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("PL", "Pollen"),
                            ("DM", "Dust Mites"),
                            ("MD", "Mold"),
                            ("GR", "Grass"),
                        ],
                        default="GR",
                        max_length=2,
                    ),
                ),
                ("reaction", models.CharField(max_length=150)),
                (
                    "severity",
                    models.CharField(
                        choices=[("MD", "Mild"), ("SV", "Severe")],
                        default="MD",
                        max_length=2,
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="petz.pets"
                    ),
                ),
            ],
        ),
    ]
