# Generated by Django 4.2 on 2025-11-04 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("petz", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="allergies", name="pet",),
        migrations.RemoveField(model_name="vaccines", name="pet",),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="petz.pets"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="allergies",
            name="record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="petz.medicalrecord",
            ),
        ),
        migrations.AddField(
            model_name="vaccines",
            name="record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="petz.medicalrecord",
            ),
        ),
    ]
