# Generated by Django 4.2 on 2025-11-04 15:11

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("petz", "0002_remove_allergies_pet_remove_vaccines_pet_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="pets", managers=[("everything", django.db.models.manager.Manager()),],
        ),
        migrations.AddField(
            model_name="pets",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
